# Generated by Django 4.2.2 on 2023-06-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
